apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- app-ingress.yaml
- booking-deployment.yaml
- booking-service.yaml
- guest-deployment.yaml
- guest-service.yaml
- hotel-webapp-deployment.yaml
- hotel-webapp-service.yaml
- room-deployment.yaml
- room-service.yaml
images:
- name: ghcr.io/hotel-landon-kb/hotel-webapp
  newName: ghcr.io/hotel-landon-kb/hotel-webapp
  newTag: "32"
- name: ghcr.io/hotel-landon-kb/room-service
  newName: ghcr.io/hotel-landon-kb/room-service
  newTag: "22"
